#!/usr/bin/env bash


# Define the path to the ZAP stable docker image
zap_docker_image="softwaresecurityproject/zap-stable"

# Pull the ZAP stable docker image
docker pull $zap_docker_image

# Loop through each URL and run ZAPit for reconnaissance scan
while read url;
do
    scan_dir=$(dir-setup zapIT)
    out_dir="$scan_dir/$()"
    echo "Scanning $url ..."
    docker run -t --rm $zap_docker_image ./zap.sh -cmd -zapit "$url" | tee $(sed 's/\./-/g' "$url")
    echo "Scan completed for $url"
    echo "============================================="
done < "$1"
